### ISSUE TITLE
There is already a tomcat9-maven-plugin in Maven Central Repository

### ISSUE THREAD

**Issue by zhoujin7** [sdumont2/tomcat9-maven-plugin#13]
There is already a tomcat9-maven-plugin in Maven Central Repository
```xml
<groupId>org.opoo.maven</groupId>
<artifactId>tomcat9-maven-plugin</artifactId>
<version>3.0.0</version>
```

**Comment by sdumont2** [comment]
That artifact comes from a different group ID and is not an official Apache plugin. 

Like mine, it's likely some variation of the https://github.com/apache/tomcat-maven-plugin original plugin. That being said, I haven't worked on this side project in awhile, so if that artifact suits your needs then by all means, please use it. 

However artifact IDs are not required to be unique in Maven Central, so this is not an issue. Closing.
